name: deploy-bot
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t mhlptl/crypto-price-bot .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DOAT}}

      - name: Log into DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Tag Image
        run: docker tag mhlptl/crypto-price-bot ${{secrets.REGISTRY}}/mhlptl/crypto-price-bot

      - name: Push to Registry
        run: docker push ${{secrets.REGISTRY}}/mhlptl/crypto-price-bot
